AWSTemplateFormatVersion: '2010-09-09'
Resources:
  AngularAppBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'angular-app-bucket-${AWS::Region}-${AWS::AccountId}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: false
        IgnorePublicAcls: true
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  AngularAppBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AngularAppBucket
      PolicyDocument:
        Statement:
          - Action: 's3:GetObject'
            Effect: Allow
            Resource: !Sub '${AngularAppBucket.Arn}/*'
            Principal: '*'

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !GetAtt AngularAppBucket.DomainName
            Id: AngularAppOrigin
            S3OriginConfig: {}
        DefaultCacheBehavior:
          TargetOriginId: AngularAppOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD]
          ForwardedValues:
            QueryString: false
        Enabled: true
        DefaultRootObject: index.html

Outputs:
  BucketName:
    Value: !Ref AngularAppBucket
  CloudFrontURL:
    Value: !GetAtt CloudFrontDistribution.DomainName